import React, { useState, useEffect } from 'react';
import {
  FileQuestion,
  Clock,
  Award,
  CheckCircle2,
  ArrowRight,
  Sparkles
} from 'lucide-react';
import { Link } from 'react-router-dom';
import api from '../../services/api';

export const QuizzesPage: React.FC = () => {
  const [quizzes, setQuizzes] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchQuizzes();
  }, []);

  const fetchQuizzes = async () => {
    setLoading(true);
    try {
      const res = await api.get('/quizzes');
      if (res.data?.success) {
        setQuizzes(res.data.data || []);
      }
    } catch {
      setQuizzes([]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold text-slate-900">Knowledge Check Quizzes</h1>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Short, modular quizzes formulated from MoSPI training documents & NSSTA curriculum.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
        {quizzes.length === 0 ? (
          <div className="col-span-full bg-white p-12 text-center rounded-2xl border border-slate-200 text-slate-500 text-xs">
            No active quizzes published at this time.
          </div>
        ) : (
          quizzes.map((quiz) => (
            <div
              key={quiz.id}
              className="bg-white rounded-2xl border border-slate-200 p-5 shadow-xs hover:border-blue-400 hover:shadow-md transition flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200">
                    PUBLISHED
                  </span>
                  <span className="text-[11px] text-slate-400 flex items-center gap-1">
                    <Clock className="w-3.5 h-3.5" />
                    {quiz.duration || 15} Mins
                  </span>
                </div>

                <h3 className="text-xs font-bold text-slate-900 leading-snug">
                  {quiz.title}
                </h3>
                <p className="text-[11px] text-slate-500 mt-1.5 line-clamp-3 leading-relaxed">
                  {quiz.description || 'Module knowledge check generated by NSSTA instructors.'}
                </p>

                <div className="mt-3 text-[11px] text-slate-400">
                  <span>Questions: {quiz.questions?.length || 5} MCQs</span>
                  <span className="mx-2">•</span>
                  <span>Pass: {quiz.passingScore || 60}%</span>
                </div>
              </div>

              <div className="mt-5 pt-3 border-t border-slate-100 flex items-center justify-between">
                <span className="text-[11px] text-slate-500 font-mono">
                  {quiz.totalMarks || 100} Marks
                </span>

                <Link
                  to={`/employee/quizzes/${quiz.id}/attempt`}
                  className="px-3.5 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-semibold shadow-xs transition flex items-center gap-1.5"
                >
                  <span>Attempt Quiz</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
